clox: main.c memory.c chunk.c debug.c value.c vm.c\
		common.h chunk.h memory.h debug.h value.h vm.h
	gcc -o clox.exe main.c memory.c chunk.c debug.c value.c vm.c\
		 common.h chunk.h memory.h debug.h value.h vm.h